### Signup
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name":"Pradeep Kumar",
    "email":"frontendweb.ak@gmail.com",
    "password":"Admin$123@",
    "mobile":"7291893481"
}

### login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email":"frontendweb.ak@gmail.com",
    "password":"Admin$123@"
}
