### Get roles
GET http://localhost:3000/api/v1/role

### Add new role
POST http://localhost:3000/api/v1/role
Content-Type: application/json

{
    "name":"guest"
}


### Update role
PUT http://localhost:3000/api/v1/role/users
Content-Type: application/json

{
    "name":"user"
}