import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

import AppProvider from "../context/root";
import { getSession } from "../core/session/session";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getSession();
	console.log("S--", session);
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AppProvider session={session!}>
					<ToastContainer />
					{children}
				</AppProvider>
			</body>
		</html>
	);
}
